### ISSUE TITLE
The library crashes on Android when closeSSEConnection() is called

### ISSUE THREAD

**Issue by westward** [heremaps/oksse#13]
Hi guys,
The library crashes in closeSSEConnection() call, the stack trace looks like:

Caused by: android.os.NetworkOnMainThreadException
  at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
  at java.net.SocketInputStream.read(SocketInputStream.java:150)
  at java.net.SocketInputStream.read(SocketInputStream.java:120)
  at okio.Okio$2.read(Okio.java:139)
  at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
  at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
  at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
  at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
  at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:463)
  at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:446)
  at okhttp3.internal.Util.skipAll(Util.java:175)
  at okhttp3.internal.Util.discard(Util.java:157)
  at okhttp3.internal.http1.Http1Codec$ChunkedSource.close(Http1Codec.java:484)
  at okio.RealBufferedSource.close(RealBufferedSource.java:455)
  at com.here.oksse.RealServerSentEvent$Reader.close(RealServerSentEvent.java:199)
  at com.here.oksse.RealServerSentEvent.close(RealServerSentEvent.java:142)
  at xx.xxxxx..controller.EventsController.closeSSEConnection(EventsController.java:140)
 
The source of trouble that at line #199 of RealServerSentEvent.java the method source.close() is called from the main thread. If the library is designed only for Java, not Android, sorry that I raised this issue. Otherwise the library should take care to correctly handle this situation. Also it should send callback events from the main thread, not the Okio execution (background) thread.

**Comment by skimarxall** [comment]
Thanks for reporting, I think a recent change might have introduced this. https://github.com/heremaps/oksse/commit/c07e9a97465cd4d36ae2cdc3f6fb4e157a941eb8

Since we use jitpack you can use a previous version to avoid this problem. I will take a look soon

https://jitpack.io/#heremaps/oksse/4271ddac93

**Comment by westward** [comment]
I will check that previous version tomorrow. But after a visual review, I think that recent change is not the source of the crash I've reported.

As I can understand, the existing library implementation has two troubles, when it's run on Android. And these two troubles has the same origin - incorrect dealing with threads.

On Android any networking must be performed on a background thread, otherwise the an application will be killed by system with a NetworkOnMainThreadException. Also it's a good practice on Android to provide callback results on a main thread, because any update of UI from a non-main thread will also ends with a runtime exception.

Unfortunately the library violates both these rules. In one hand, it calls the callback listener directly from the Okio thread. In other hand, it calls Okio close() method from the main thread that kills the application  with NetworkOnMainThreadException.

IMO the right way is to use two android.os.Handler classes, one to send control messages like close form main to SSE thread, another one to send callback events from SSE thread to main one.  It's also possible to use RxJava with it's useful ability to deal with threads and make the library "reactive".

**Comment by skimarxall** [comment]
Hi,

I pushed a fix to remove the source.close since it was not necessary, now is safe to call close again from main thread.

Regarding how this library works. The main consideration is to be an extension of OkHttp library providing extra functionality for SSE protocol. Once said that, note that OkHttp is a Java library and most of the methods are not safe to call from the main thread in android. Thus it is the responsibility of the user of the library to handle the threading part. 

Meaning that the methods in the listener could be called from any thread, thus you should handle that.

For now the idea is to keep this library pure java so, there is no intention to add the Handlers. I might document it better and add some annotations.

**Comment by westward** [comment]
Hi,
Thank you for the provided fix. I may confirm that now the library doesn't crashes the app on a close() call.
Also I provided a transferring the library callback events to main thread to be Android good citizen. 
Finally, I want to say that I'm not a Java or Android guru. But IMO the library should always works when it's methods (like close()) are called. So I'm very happy that the fix is provided to the library. :) Thank you!
