### ISSUE TITLE
StrictMode error: Explicit termination method 'response.body().close()' not called

### ISSUE THREAD

**Issue by RyanRamchandar** [heremaps/oksse#17]
The following code throws a StrictMode error:
```kotin
val request = Request.Builder().url(url).build()
val okSse = OkSse(client)
sse = okSse.newServerSentEvent(request, listener())
```

```
04-04 14:58:32.269 7907-8257/co.app.debug E/StrictMode: A resource was acquired at attached
 stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'response.body().close()' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:184)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at okhttp3.internal.platform.AndroidPlatform$CloseGuard.createAndOpen(AndroidPlatform.java:340)
        at okhttp3.internal.platform.AndroidPlatform.getStackTraceForCloseable(AndroidPlatform.java:155)
        at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
        at okhttp3.RealCall.enqueue(RealCall.java:98)
        at com.here.oksse.RealServerSentEvent.enqueue(RealServerSentEvent.java:66)
        at com.here.oksse.RealServerSentEvent.connect(RealServerSentEvent.java:49)
        at com.here.oksse.OkSse.newServerSentEvent(OkSse.java:90)
        ... app stack
```

Version:
```
implementation "com.github.heremaps:oksse:0c60781b9a"
```

**Comment by RyanRamchandar** [comment]
These warnings seemed to have resurfaced after: #14

**Comment by RyanRamchandar** [comment]
@skimarxall we setup Strict mode like so:

```
StrictMode.setThreadPolicy(StrictMode.ThreadPolicy.Builder()
        .detectAll()
        .penaltyLog()
        .build())
StrictMode.setVmPolicy(StrictMode.VmPolicy.Builder()
        .detectAll()
        .penaltyLog()
        .build())
```

**Comment by skimarxall** [comment]
I did not try the VM policy either with the penalty log, I will, but as mentioned in the other comment is it safe to call cancel from any thread

**Comment by bruestel** [comment]
I think my PR is resolving this. https://github.com/heremaps/oksse/pull/24

**Comment by skimarxall** [comment]
I just merged the fix, please try the new version and let me know if the warning is solved

**Comment by skimarxall** [comment]
@kashesoft could you make sure you are using the last version and if so, copy the logcat and the strict policy configuration you are using?

**Comment by kashesoft** [comment]
Yes, we are using
```StrictMode.setThreadPolicy(StrictMode.ThreadPolicy.Builder()
        .detectAll()
        .penaltyLog()
        .build())
StrictMode.setVmPolicy(StrictMode.VmPolicy.Builder()
        .detectAll()
        .penaltyLog()
        .build())```

Logcat:
```10-09 09:35:52.799 20249-20969/co.umbrela.launcher.debug E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'response.body().close()' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:184)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at okhttp3.internal.platform.AndroidPlatform$CloseGuard.createAndOpen(AndroidPlatform.java:340)
        at okhttp3.internal.platform.AndroidPlatform.getStackTraceForCloseable(AndroidPlatform.java:155)
        at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
        at okhttp3.RealCall.enqueue(RealCall.java:98)
        at com.here.oksse.RealServerSentEvent.enqueue(RealServerSentEvent.java:70)
        at com.here.oksse.RealServerSentEvent.connect(RealServerSentEvent.java:50)
        at com.here.oksse.OkSse.newServerSentEvent(OkSse.java:90)
        ...```
